apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ops
  labels:
    app: kafka-ops
spec:
  selector:
    matchLabels:
      app: kafka-ops
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-ops
    spec:
      containers:
        - name: kafka-ops
          image: 471108701394.dkr.ecr.us-east-1.amazonaws.com/arln/kafka-ops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 11000
          envFrom:
            - configMapRef:
                name: aa-kafka

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-ops
  name: kafka-ops
  namespace: default
spec:
  ports:
    - port: 11000
  selector:
    app: kafka-ops
