apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakfa-ops
  labels:
    app: kakfa-ops
spec:
  selector:
    matchLabels:
      app: kakfa-ops
  replicas: 1
  template:
    metadata:
      labels:
        app: kakfa-ops
    spec:
      containers:
        - name: kafka-ops
          image: 471108701394.dkr.ecr.us-east-1.amazonaws.com/arln/kakfa-ops:<VERSION>
          imagePullPolicy: Always
          ports:
            - containerPort: 11000
          envFrom:
            - configMapRef:
                name: kakfa-ops-configmap

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kakfa-ops
  name: kakfa-ops
  namespace: default
spec:
  ports:
    - port: 11000
  selector:
    app: kakfa-ops