---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.provider: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: kafka-ops.daart-qa.eks.sandbox.aimsplatform.com
  labels:
    app: kafka-ops
    version: "0.1"
  name: kafka-ops
spec:
  rules:
  - host: kafka-ops.daart-qa.eks.sandbox.aimsplatform.com
    http:
      paths:
      - backend:
          serviceName: kafka-ops
          servicePort: 11000
        path: /
  tls:
  - hosts:
    - kafka-ops.daart-qa.eks.sandbox.aimsplatform.com
    secretName: kafka-ops-daart-qa-eks-sandbox-aimsplatform-com-tls
