---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: kafka-ops
    version: "0.1"
  name: kafka-ops
spec:
  ports:
  - name: commplex-main
    port: 11000
    protocol: TCP
    targetPort: 11000
  selector:
    app: kafka-ops
